import sanitizeHtml from 'sanitize-html';

const colorPattern = /^(?:#[0-9a-fA-F]{3,8}|rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}(?:\s*,\s*(?:0|1|0?\.\d+))?\s*\)|hsla?\(\s*\d{1,3}(?:deg)?\s*,\s*\d{1,3}%\s*,\s*\d{1,3}%(?:\s*,\s*(?:0|1|0?\.\d+))?\s*\)|[a-zA-Z]+)$/;
const lengthPattern = /^(?:0|\d+(?:\.\d+)?(?:px|rem|em|%))$/;

export const modalHtmlSanitizeOptions = {
  allowedTags: [
    'br',
    'button',
    'code',
    'datalist',
    'dd',
    'div',
    'dl',
    'dt',
    'em',
    'h2',
    'h3',
    'h4',
    'input',
    'label',
    'li',
    'ol',
    'option',
    'p',
    'pre',
    'select',
    'span',
    'strong',
    'table',
    'tbody',
    'td',
    'textarea',
    'th',
    'thead',
    'tr',
    'ul',
  ],
  allowedAttributes: {
    '*': [
      'aria-hidden',
      'aria-label',
      'class',
      'id',
      'role',
      'tabindex',
      'title',
    ],
    button: ['aria-label', 'class', 'data-index', 'disabled', 'id', 'title', 'type'],
    datalist: ['id'],
    div: ['aria-label', 'class', 'data-index', 'id', 'role', 'style', 'tabindex', 'title'],
    input: [
      'autocomplete',
      'checked',
      'class',
      'id',
      'list',
      'max',
      'min',
      'name',
      'placeholder',
      'step',
      'type',
      'value',
    ],
    label: ['class', 'for', 'role', 'style', 'tabindex', 'title'],
    option: ['disabled', 'selected', 'value'],
    select: ['class', 'id', 'name', 'value'],
    span: ['aria-hidden', 'class', 'id', 'style', 'title'],
    td: ['class', 'colspan', 'id'],
    textarea: ['autocomplete', 'class', 'id', 'name', 'placeholder', 'rows', 'value'],
    th: ['class', 'colspan', 'id', 'scope'],
  },
  allowedSchemes: ['http', 'https', 'mailto'],
  allowedStyles: {
    '*': {
      'align-items': [/^(?:baseline|center|flex-end|flex-start|stretch)$/],
      'background-color': [colorPattern],
      'border': [/^\d+(?:\.\d+)?px\s+solid\s+(?:#[0-9a-fA-F]{3,8}|[a-zA-Z]+)$/],
      'border-radius': [lengthPattern],
      'cursor': [/^(?:default|pointer)$/],
      'display': [/^(?:block|flex|grid|inline|inline-block|none)$/],
      'flex-wrap': [/^(?:nowrap|wrap|wrap-reverse)$/],
      'gap': [lengthPattern],
      'height': [lengthPattern],
      'width': [lengthPattern],
    },
  },
  allowProtocolRelative: false,
  disallowedTagsMode: 'discard',
  enforceHtmlBoundary: true,
};

export function sanitizeModalHtml(html) {
  return sanitizeHtml(String(html ?? ''), modalHtmlSanitizeOptions);
}
